version: '3.7'
services:
  apache:
    image: httpd:2.4
    container_name: apache-${PROJECT_NAME}
    ports:
      - ${APACHE_PORT}:80
    volumes:
      - ./web/build/:/usr/local/apache2/htdocs/
    env_file:
      - .env
    depends_on:
      - php
  php:
    build: .
    container_name: php-${PROJECT_NAME}
    ports: 
      - ${PHP_PORT}:80
    volumes:
      - ./api/:/var/www/html/api/
    env_file:
      - .env   
  mysql:
    image: mysql:5.7
    container_name: mysql-${PROJECT_NAME}
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=oca
      - TZ=America/Guatemala
    volumes:
      - ${MYSQL_VOLUMES}:/var/lib/mysql 
    env_file:
      - .env
  mssql: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-${PROJECT_NAME}
    ports:
      - ${MSSQL_SERVER_PORT}:1433
    environment:
      - SA_PASSWORD=${MSSQL_PASSWORD}
      - ACCEPT_EULA=Y
      - TZ=America/Guatemala
    volumes:
      - ${MSSQL_VOLUMES}:/var/opt/mssql/data
    env_file:
      - .env    
